spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shiro?useSSL=false
    username: root
    password: 123456
  output:
    ansi:
     enabled:always
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  thymeleaf:
    cache: false    #该配置在开发的时候关掉，在实际环境中开取，提高渲染的效率
    prefix: classpath:/templates
    suffix: .html
    encoding: utf-8
    servlet.content-type: text/html
    mode: HTML5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 0

logging:
  file: "logs/spring-boot.log"
  config: classpath:logback.xml
server:
  port: 10252

info:
  contact:
    email: zhjames17@foxmail.com
    phone:  "nice to meet you, nophone"

prop:
  name: zhuhj

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
